# Generated by Django 5.2.4 on 2025-07-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('image_url', models.URLField(blank=True, help_text='Enter the URL for the project image.', null=True, verbose_name='Image URL')),
                ('project_link', models.URLField(blank=True, help_text='Live or source code link for the project.', null=True, verbose_name='Project Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Service Title')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('icon_svg_html', models.TextField(help_text='Enter the full HTML for the SVG icon here.', verbose_name='Icon SVG')),
                ('icon_bg_color', models.CharField(default='bg-gray-100', help_text='Background color for the icon (e.g., bg-teal-100)', max_length=50, verbose_name='Icon Background Color')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Technology Name')),
                ('icon_svg_html', models.TextField(help_text='Enter the full HTML for the SVG icon here.', verbose_name='Icon SVG')),
                ('icon_bg_color', models.CharField(default='bg-gray-100', help_text='Background color for the icon (e.g., bg-red-100)', max_length=50, verbose_name='Icon Background Color')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Check this if highlighted.', verbose_name='Is Highlighted?')),
            ],
        ),
    ]
