# Generated by Django 5.2.4 on 2025-07-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='card_color_class',
            field=models.CharField(default='bg-gray-300', help_text='Tailwind CSS class for the card background (e.g., bg-blue-200, bg-teal-500).', max_length=50, verbose_name='Card Color Class'),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='', max_length=200, verbose_name='Project Subtitle (e.g., Interactive Dashboards)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Project Title (e.g., Project Alpha)'),
        ),
    ]
